import { Conference, Committee, User } from "./types";

export const COMMITTEES: Committee[] = [
  { id: "unsc", name: "UN Security Council", abbreviation: "UNSC", topic1: "Cybersecurity Threats to Critical Infrastructure", topic2: "The Crisis in the Taiwan Strait", difficulty: "Advanced", size: 15 },
  { id: "unga", name: "UN General Assembly", abbreviation: "UNGA", topic1: "Universal Access to Clean Water", topic2: "Digital Divide in Developing Nations", difficulty: "Intermediate", size: 193 },
  { id: "unhcr", name: "UN Refugee Agency", abbreviation: "UNHCR", topic1: "Climate Refugees and Legal Frameworks", topic2: "Stateless Persons & Right to Identity", difficulty: "Intermediate", size: 60 },
  { id: "eco", name: "Economic & Social Council", abbreviation: "ECOSOC", topic1: "Global Debt Crisis and Developing Nations", topic2: "Future of AI in Global Labor Markets", difficulty: "Advanced", size: 54 },
  { id: "who", name: "World Health Organization", abbreviation: "WHO", topic1: "Pandemic Preparedness Post-COVID-19", topic2: "Mental Health as a Global Priority", difficulty: "Beginner", size: 80 },
  { id: "disec", name: "Disarmament Committee", abbreviation: "DISEC", topic1: "Autonomous Weapons Systems (Killer Robots)", topic2: "Nuclear Proliferation in the Modern Era", difficulty: "Advanced", size: 40 },
  { id: "sochum", name: "Social, Humanitarian & Cultural", abbreviation: "SOCHUM", topic1: "Rights of Indigenous Peoples", topic2: "Gender Equality in Post-Conflict States", difficulty: "Beginner", size: 65 },
  { id: "iaea", name: "International Atomic Energy Agency", abbreviation: "IAEA", topic1: "Nuclear Energy as a Climate Solution", topic2: "Monitoring Non-Proliferation Treaties", difficulty: "Intermediate", size: 35 },
];

export const CONFERENCES: Conference[] = [
  {
    id: "1",
    title: "Singapore International MUN",
    slug: "singapore-international-mun",
    location: "Raffles City Convention Centre, Singapore",
    city: "Singapore",
    country: "Singapore",
    region: "Asia",
    startDate: "June 12, 2026",
    endDate: "June 15, 2026",
    registrationDeadline: "May 1, 2026",
    price: 120,
    currency: "USD",
    level: "High School",
    committees: [COMMITTEES[0], COMMITTEES[2], COMMITTEES[6]],
    capacity: 600,
    registered: 487,
    description: "The premier MUN conference in Southeast Asia, bringing together 600 delegates from over 50 countries. SIMUN is renowned for its rigorous academic standards, world-class guest speakers, and unparalleled networking opportunities.",
    organizer: "Singapore MUN Society",
    organizerEmail: "info@simun.sg",
    website: "https://simun.sg",
    featured: true,
    color: "from-blue-600 to-indigo-700",
    tags: ["Featured", "High School", "In-Person"],
  },
  {
    id: "2",
    title: "Harvard WorldMUN",
    slug: "harvard-worldmun",
    location: "Palais des congrès, Montreal, Canada",
    city: "Montreal",
    country: "Canada",
    region: "Americas",
    startDate: "March 20, 2026",
    endDate: "March 24, 2026",
    registrationDeadline: "February 1, 2026",
    price: 180,
    currency: "USD",
    level: "University",
    committees: [COMMITTEES[0], COMMITTEES[1], COMMITTEES[3], COMMITTEES[5]],
    capacity: 3000,
    registered: 2650,
    description: "Harvard WorldMUN is one of the largest and most prestigious MUN conferences in the world. Run by Harvard students for university-level delegates globally, WorldMUN challenges delegates with rigorous debate and complex geopolitical scenarios.",
    organizer: "Harvard International Relations Council",
    organizerEmail: "worldmun@harvard.edu",
    website: "https://worldmun.org",
    featured: true,
    color: "from-red-700 to-rose-800",
    tags: ["Elite", "University", "In-Person"],
  },
  {
    id: "3",
    title: "Oxford Global MUN",
    slug: "oxford-global-mun",
    location: "Bodleian Library, Oxford, UK",
    city: "Oxford",
    country: "United Kingdom",
    region: "Europe",
    startDate: "July 5, 2026",
    endDate: "July 8, 2026",
    registrationDeadline: "May 20, 2026",
    price: 150,
    currency: "GBP",
    level: "Elite",
    committees: [COMMITTEES[0], COMMITTEES[3], COMMITTEES[7]],
    capacity: 400,
    registered: 312,
    description: "Oxford Global MUN is an exclusive conference set against the historic backdrop of Oxford University. Its intimate size ensures every delegate receives the attention they deserve, debating complex international topics with peers from top universities worldwide.",
    organizer: "Oxford International Relations Society",
    organizerEmail: "info@oxfordglobalmun.com",
    website: "https://oxfordglobalmun.com",
    featured: false,
    color: "from-navy-800 to-slate-900",
    tags: ["Elite", "University", "In-Person"],
  },
  {
    id: "4",
    title: "Delhi University MUN",
    slug: "delhi-university-mun",
    location: "Delhi University Campus, New Delhi, India",
    city: "New Delhi",
    country: "India",
    region: "Asia",
    startDate: "August 10, 2026",
    endDate: "August 12, 2026",
    registrationDeadline: "July 15, 2026",
    price: 40,
    currency: "USD",
    level: "University",
    committees: [COMMITTEES[1], COMMITTEES[2], COMMITTEES[4], COMMITTEES[6]],
    capacity: 800,
    registered: 340,
    description: "DUMUN is one of India's largest university-level conferences, fostering diplomatic discourse on pressing global issues. Known for its excellent hospitality, DUMUN offers an immersive experience at a highly accessible price point.",
    organizer: "Delhi University MUN Council",
    organizerEmail: "contact@dumun.in",
    website: "https://dumun.in",
    featured: false,
    color: "from-orange-500 to-amber-600",
    tags: ["University", "In-Person", "South Asia"],
  },
  {
    id: "5",
    title: "Berlin Model Nations",
    slug: "berlin-model-nations",
    location: "Humboldt Forum, Berlin, Germany",
    city: "Berlin",
    country: "Germany",
    region: "Europe",
    startDate: "September 18, 2026",
    endDate: "September 21, 2026",
    registrationDeadline: "August 1, 2026",
    price: 90,
    currency: "EUR",
    level: "High School",
    committees: [COMMITTEES[2], COMMITTEES[4], COMMITTEES[6]],
    capacity: 500,
    registered: 210,
    description: "BERMUN is a prestigious conference in the heart of Berlin, hosted at the iconic Humboldt Forum. With its unique focus on European affairs and global human rights, BERMUN attracts delegates from across Europe and beyond.",
    organizer: "Humboldt MUN Association",
    organizerEmail: "info@bermun.de",
    website: "https://bermun.de",
    featured: false,
    color: "from-zinc-700 to-stone-800",
    tags: ["High School", "In-Person", "Europe"],
  },
  {
    id: "6",
    title: "Yale MUN (YMUN)",
    slug: "yale-mun",
    location: "Yale School of Management, New Haven, USA",
    city: "New Haven",
    country: "United States",
    region: "Americas",
    startDate: "January 22, 2027",
    endDate: "January 25, 2027",
    registrationDeadline: "November 30, 2026",
    price: 110,
    currency: "USD",
    level: "Elite",
    committees: [COMMITTEES[0], COMMITTEES[3], COMMITTEES[5], COMMITTEES[7]],
    capacity: 2000,
    registered: 1780,
    description: "Yale Model United Nations is one of the oldest and most decorated MUN conferences in North America. YMUN brings together the world's top delegates for four days of rigorous policy debate, leadership development, and unparalleled networking.",
    organizer: "Yale International Relations Association",
    organizerEmail: "ymun@yale.edu",
    website: "https://ymun.yale.edu",
    featured: true,
    color: "from-blue-900 to-indigo-950",
    tags: ["Elite", "University", "In-Person"],
  },
  {
    id: "7",
    title: "Tokyo Global Leaders MUN",
    slug: "tokyo-global-leaders-mun",
    location: "Tokyo International Forum, Japan",
    city: "Tokyo",
    country: "Japan",
    region: "Asia",
    startDate: "October 3, 2026",
    endDate: "October 6, 2026",
    registrationDeadline: "August 20, 2026",
    price: 95,
    currency: "USD",
    level: "Open",
    committees: [COMMITTEES[1], COMMITTEES[3], COMMITTEES[4]],
    capacity: 700,
    registered: 290,
    description: "TGLMUN focuses on East Asian geopolitics, sustainability, and technology ethics. Hosted at the stunning Tokyo International Forum, this conference provides a unique East-West cultural perspective on global governance.",
    organizer: "Tokyo IR Forum",
    organizerEmail: "info@tglmun.jp",
    website: "https://tglmun.jp",
    featured: false,
    color: "from-rose-600 to-pink-700",
    tags: ["Open", "In-Person", "Asia Pacific"],
  },
  {
    id: "8",
    title: "Cape Town Global Think MUN",
    slug: "cape-town-global-think-mun",
    location: "Cape Town International Convention Centre, South Africa",
    city: "Cape Town",
    country: "South Africa",
    region: "Africa",
    startDate: "November 14, 2026",
    endDate: "November 17, 2026",
    registrationDeadline: "October 1, 2026",
    price: 55,
    currency: "USD",
    level: "Open",
    committees: [COMMITTEES[2], COMMITTEES[4], COMMITTEES[6]],
    capacity: 400,
    registered: 120,
    description: "CTGTMUN champions the African perspective in global diplomacy. With a strong focus on climate, development, and pan-African unity, this conference brings together Africa's brightest young minds in a truly inspiring setting.",
    organizer: "Cape Town UN Association",
    organizerEmail: "info@ctgtmun.org",
    website: "https://ctgtmun.org",
    featured: false,
    color: "from-teal-600 to-green-700",
    tags: ["Open", "In-Person", "Africa"],
  },
  {
    id: "9",
    title: "Vienna International MUN",
    slug: "vienna-international-mun",
    location: "Vienna International Centre (UN Campus), Austria",
    city: "Vienna",
    country: "Austria",
    region: "Europe",
    startDate: "May 7, 2026",
    endDate: "May 10, 2026",
    registrationDeadline: "March 15, 2026",
    price: 130,
    currency: "EUR",
    level: "University",
    committees: [COMMITTEES[0], COMMITTEES[5], COMMITTEES[7]],
    capacity: 350,
    registered: 320,
    description: "VIMUN is held at the actual UN Campus in Vienna — one of the four major UN headquarters in the world. This lends an authenticity to the conference that is unrivaled, with delegates debating in the very rooms used by real UN bodies.",
    organizer: "Vienna UN Youth Association",
    organizerEmail: "info@vimun.at",
    website: "https://vimun.at",
    featured: true,
    color: "from-purple-600 to-violet-700",
    tags: ["University", "In-Person", "Europe", "Featured"],
  },
  {
    id: "10",
    title: "MUN Online Global Summit",
    slug: "mun-online-global-summit",
    location: "Virtual — Zoom / Discord",
    city: "Virtual",
    country: "Global",
    region: "Americas",
    startDate: "December 5, 2026",
    endDate: "December 7, 2026",
    registrationDeadline: "November 20, 2026",
    price: 25,
    currency: "USD",
    level: "Hybrid",
    committees: [COMMITTEES[1], COMMITTEES[2], COMMITTEES[4], COMMITTEES[6]],
    capacity: 2000,
    registered: 450,
    description: "The world's premier online MUN conference, accessible from anywhere on the globe. MOGS removes geographic barriers and brings together thousands of delegates in a fully virtual, highly interactive environment with live streaming, breakout sessions, and digital lobbying.",
    organizer: "Global MUN Foundation",
    organizerEmail: "info@mogs.world",
    website: "https://mogs.world",
    featured: false,
    color: "from-cyan-500 to-blue-600",
    tags: ["Hybrid", "Virtual", "Beginner Friendly"],
  },
  {
    id: "11",
    title: "Sydney Pacific MUN",
    slug: "sydney-pacific-mun",
    location: "International Convention Centre, Sydney, Australia",
    city: "Sydney",
    country: "Australia",
    region: "Oceania",
    startDate: "February 20, 2027",
    endDate: "February 23, 2027",
    registrationDeadline: "January 5, 2027",
    price: 85,
    currency: "AUD",
    level: "Open",
    committees: [COMMITTEES[1], COMMITTEES[3], COMMITTEES[6]],
    capacity: 450,
    registered: 180,
    description: "SPMUN brings together the brightest young diplomats from the Asia-Pacific region and beyond. With a strong emphasis on climate change and Pacific geopolitics, this conference offers a uniquely regional perspective on global governance.",
    organizer: "Sydney IR Society",
    organizerEmail: "info@spmun.org.au",
    website: "https://spmun.org.au",
    featured: false,
    color: "from-sky-500 to-blue-600",
    tags: ["Open", "In-Person", "Oceania"],
  },
  {
    id: "12",
    title: "Dubai World Leaders Summit MUN",
    slug: "dubai-world-leaders-mun",
    location: "Dubai World Trade Centre, UAE",
    city: "Dubai",
    country: "United Arab Emirates",
    region: "Asia",
    startDate: "April 8, 2027",
    endDate: "April 11, 2027",
    registrationDeadline: "February 28, 2027",
    price: 200,
    currency: "USD",
    level: "Elite",
    committees: [COMMITTEES[0], COMMITTEES[3], COMMITTEES[5], COMMITTEES[7]],
    capacity: 500,
    registered: 310,
    description: "DWL-MUN is the Middle East's most prestigious MUN conference. Held at the world-class Dubai World Trade Centre, it combines rigorous academic debate with exceptional hospitality, attracting delegates from over 70 countries. Known for its lavish gala and industry partnerships.",
    organizer: "Dubai IR & Diplomacy Council",
    organizerEmail: "info@dwlmun.ae",
    website: "https://dwlmun.ae",
    featured: true,
    color: "from-amber-500 to-orange-600",
    tags: ["Elite", "In-Person", "Middle East", "Featured"],
  },
];

export const MOCK_USER: User = {
  id: "u1",
  name: "Alex Chen",
  email: "alex.chen@university.edu",
  avatar: "AC",
  school: "National University of Singapore",
  country: "Singapore",
  registeredConferences: [
    {
      id: "reg1",
      conferenceId: "1",
      conferenceTitle: "Singapore International MUN",
      committeeId: "unsc",
      committeeName: "UN Security Council",
      country: "France",
      status: "Confirmed",
      registeredAt: "March 15, 2026",
      paid: true,
      amount: 120,
    },
  ],
};
