// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Prefer DIRECT_URL for migrations. On Supabase, if db.*.supabase.co:5432 fails (IPv4-only),
    // use the Supavisor session pooler :5432 URL instead — same pattern as DATABASE_URL but port 5432
    // without ?pgbouncer=true. See https://supabase.com/docs/guides/database/prisma
    url: process.env["DIRECT_URL"]?.trim() || process.env["DATABASE_URL"],
  },
});
